README.md
The original content appears to be based on https://aws.amazon.com/blogs/aws/new-for-aws-lambda-container-image-support/
Unfortunately when it was copied, the entrypoint script was collapsed down to a single line and part of it was lost. A handful of other improvements are also included.
=> chore: fix poorly formatted README.md section

cmd/aws-lambda-rie/handlers.go
Lambda now supports millisecond billing granularity (https://aws.amazon.com/blogs/aws/new-for-aws-lambda-1ms-billing-granularity-adds-cost-savings/), so this PR switches the `Billed duration` to millisecond granularity to match. ✨
---
=> Use millisecond billing granularity

README.md
Change : correct from "x84-64" to "x86-64"
=> Correct a misspell in README.MD

README.md
*Issue #, if available:* N/A
The key is `AWS_LAMBDA_FUNCTION_MEMORY_SIZE`, not
`AWS_LAMBDA_MEMORY_SIZE` (see its usage in the code [1])
[1] https://github.com/aws/aws-lambda-runtime-interface-emulator/blob/6a74e68cb79a256b771210e7c46a0ca2e1cea61b/lambda/rapidcore/env/constants.go#L26
=> Fix name of memory env var in README

cmd/aws-lambda-rie/handlers.go, test/integration/local_lambda/end-to-end-test.py, test/integration/testdata/main.py
https://github.com/aws/aws-lambda-runtime-interface-emulator/issues/11
Adds support for `lambda-runtime-invoked-function-arn` header.
=> fix: Add a fake arn to Context

lambda/core/directinvoke/directinvoke.go, lambda/interop/model.go, lambda/rapid/start.go, lambda/rapidcore/server.go, lambda/rapidcore/standalone/invokeHandler.go, lambda/testdata/flowtesting.go, test/integration/local_lambda/end-to-end-test.py, test/integration/testdata/main.py
aws/aws-sam-cli#2519
Pull upstream changes from AWS Lambda. Fixes an issue from SAM cli where getRemainingTimeInMillis is returning a unix time.
=> Pull upstream changes 2021/06

README.md
*Issue #, if available:* #31
*Description of changes:* Just fixes the ordering of options in "Test an image without adding RIE to the image" example commands.  See issue #31 for details.
=> docs: Fix ordering of options in example

test/integration/local_lambda/test_end_to_end.py
These tests were lost during the commit for arm64 support, since tests file name changed.
*Description of changes:* Bring some tests back and sort the port numbers used for different architectures.
=> fix: Bring back "remaining time" tests

README.md
Removing the trailing whitespace in the README.md to improve the formatting and readability of the file.
=> docs: removing trailing whitespace

README.md
Add Shield.io badges for Go version and GitHub release. Useful for displaying important information in a visually appealing and easily accessible way at a glance.
Updated the license badge to standard Shield.io format. As it appears it was incorrect pointing to the badge for 'aws-sam-local'.
=> docs: adding Go version/release badges

README.md
The content for some bullet points are not correctly indented or spaced. This causes text and code blocks to not be displayed properly, causing confusion for customers.
This change indents the content of the bullet points so it is now correctly displayed increasing readability.
=> docs: corrected bullet point's content spacing/indentation

README.md
Adds some things from #68 that were omitted from #81, and also some other improvements.  See individual commits for details.
------
=> Readme: Add syntax highlighting, fix typos, other cleanups

.github/workflows/integ-tests.yml
- Added a Github workflow to run integrations tests on every PR. 
- Used environments approval workflow to only run the tests when someone on the team approves it (excluding the person that sent the PR).
Tests:
In order to test, we need to create a dummy PR and verify the following:
- An approval is required to run the workflow
- The workflow successfully runs when someone approves it.
=> Added automated integration tests runs on github (requires approval)

test/integration/local_lambda/test_end_to_end.py
- Refactored end-to-end tests to reduce duplicated code.
Run the following commands
- docker run --rm --privileged multiarch/qemu-user-static --reset -p yes
- sudo make integ-tests-with-docker
=> Refactored end-to-end tests

.github/workflows/integ-tests.yml, Makefile, test/integration/local_lambda/test_end_to_end.py, test/integration/testdata/Dockerfile-allinone
- refactor testcases to
- use python3.12
- respect docker arch
- run different arch in parallel gh actions
=> refactor test cases

cmd/aws-lambda-rie/handlers.go, test/integration/local_lambda/test_end_to_end.py, test/integration/testdata/main.py
*Issue #, if available:* 
Fixes #74 (and enables for https://github.com/aws/aws-sam-cli/issues/1177)
As explained in the [Lambda Invoke documentation](https://docs.aws.amazon.com/lambda/latest/dg/API_Invoke.html), the client context is passed base64-encoded in the `X-Amz-Client-Context` header.
=> Allow for user-defined client context

.github/workflows/release.yml
Created a workflow for automated releases. You still have to manually trigger the Release workflow, but all you have to do is give it the release version number and run the Action.
=> Added workflow for automated releases

.github/workflows/integ-tests.yml, .github/workflows/release.yml, Makefile, cmd/aws-lambda-rie/handlers.go, go.mod, test/integration/local_lambda/test_end_to_end.py, test/integration/testdata/Dockerfile-allinone, test/integration/testdata/main.py
=> Changes for 1.19

.github/workflows/check-binaries.yml, Makefile
Run a vulnerability check over the released binaries. 
If there are vulnerabilities in the latest released binaries, then create an issue to call this out. Before creating the ticket, check if the vulnerabilities still exist when rebuilding the binaries with the same code, and include that info in the new issue. 
Example issue: https://github.com/valerena/aws-lambda-runtime-interface-emulator/issues/4
There's an improvement to be made to only create the issue if no issue has been created already. That's coming as a future improvement. 
=> Add automatic vulnerabilities check for released binaries

.github/workflows/check-binaries.yml
Last run failed in the initial check step and it still created an issue: https://github.com/aws/aws-lambda-runtime-interface-emulator/actions/runs/9370459148
=> Run next steps only when binary check happens

.github/workflows/check-binaries.yml, Makefile
=> Merge check for vulnerabilities to main

test/integration/local_lambda/test_end_to_end.py
The tests on GitHub run on x86 instances (because arm64 instances don't have Docker installed) so when running the arm64 tests, invokes take longer because of the cross-architecture emulation. This caused that some tests that check remaining time in the function were not landing on the correct time range.
It's unknown why this delay started manifesting more consistently.
https://github.com/aws/aws-lambda-runtime-interface-emulator/actions/runs/11376296766/job/31843773742?pr=135
=> test: Add delay for time-related arm64 tests

Makefile, go.mod, lambda/rapi/handler/agentnext.go, lambda/rapi/handler/agentregister.go, lambda/rapi/handler/runtimelogs.go, lambda/rapid/handlers.go
New format requirement in go 1.24:
lambda/rapid/handlers.go:246:23: non-constant format string in call to fmt.Errorf
Fix example: Instead of fmt.Printf(variableFormatString, value), use fmt.Printf("This is a %s: %d", "string", value)
=> chore(deps): Update to Go 1.24
